version: '3.9'
services:
  db:
    image: postgres:15
    # volumes:
    #   - ./backend/app/db/postgresql/data:/var/lib/postgresql/data
    #   - ./backend/app/db/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C

  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./dockerfiles/dockerfile_backend
    # volumes:
    #   - ./backend:/app/backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}  # DB接続情報

