FROM python:3.12
WORKDIR .
RUN mkdir -p ./backend
RUN mkdir -p ./static
COPY ./backend ./backend
COPY ./static  ./static
EXPOSE 8080
WORKDIR ./backend
RUN pip install --no-cache-dir -r requirements.txt
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]

