FROM python:3.12
WORKDIR /app
RUN mkdir -p ./backend
RUN mkdir -p ./static
RUN mkdir -p ./compile_resource
COPY ./backend /app/backend
COPY ./static  /app/static
COPY ./compile_resource /app/compile_resource
EXPOSE 8080
WORKDIR /app/backend
# Install leaks command
RUN apt-get update && apt-get install -y valgrind
RUN pip install --no-cache-dir -r requirements.txt
ENV PYTHONUNBUFFERED=1
CMD ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"]
