"""return to origin

Revision ID: 07b6018e2a73
Revises: 1be8a88bc99a
Create Date: 2025-02-21 01:34:37.479034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b6018e2a73'
down_revision: Union[str, None] = '1be8a88bc99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'submission', 'problems', ['problem_id'], ['problem_id'])
    op.create_foreign_key(None, 'submission', 'users', ['user_name'], ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_constraint(None, 'submission', type_='foreignkey')
    # ### end Alembic commands ###
