"""modified submission

Revision ID: 1be8a88bc99a
Revises: c4bd6bd1ed0c
Create Date: 2025-02-20 22:39:52.409205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1be8a88bc99a'
down_revision: Union[str, None] = 'c4bd6bd1ed0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'submitted_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'submitted_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
