"""made date String

Revision ID: 303336b851ad
Revises: 9973ce4e1469
Create Date: 2025-02-21 16:08:37.327169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '303336b851ad'
down_revision: Union[str, None] = '9973ce4e1469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'input_file_content', 'testcase_with_path', ['testcase_id'], ['testcase_id'])
    op.alter_column('problems', 'open_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('problems', 'close_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problems', 'close_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="close_date::timestamp without time zone")
    op.alter_column('problems', 'open_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="open_date::timestamp without time zone")
    # op.drop_constraint(None, 'input_file_content', type_='foreignkey')
    # ### end Alembic commands ###
