"""made SubmissionResult.testcase_id to SubmissionResult.testcase_number

Revision ID: 39ac4c5f111a
Revises: 303336b851ad
Create Date: 2025-02-21 22:39:32.280304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ac4c5f111a'
down_revision: Union[str, None] = '303336b851ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_result', sa.Column('testcase_number', sa.Integer(), nullable=False))
    op.drop_constraint('submission_result_testcase_id_fkey', 'submission_result', type_='foreignkey')
    op.drop_column('submission_result', 'testcase_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_result', sa.Column('testcase_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('submission_result_testcase_id_fkey', 'submission_result', 'testcase_with_path', ['testcase_id'], ['testcase_id'])
    op.drop_column('submission_result', 'testcase_number')
    # ### end Alembic commands ###
