"""add SubmissionResult.output_content

Revision ID: 451d40032884
Revises: 39ac4c5f111a
Create Date: 2025-02-21 23:54:32.772094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451d40032884'
down_revision: Union[str, None] = '39ac4c5f111a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_result', sa.Column('output_content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_result', 'output_content')
    # ### end Alembic commands ###
