"""added math filed to problem

Revision ID: 4552aebc3d83
Revises: 6a0b6d078ef0
Create Date: 2025-03-27 12:48:13.106634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4552aebc3d83'
down_revision: Union[str, None] = '6a0b6d078ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('math', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'math')
    # ### end Alembic commands ###
