"""added input_file_content in testcase

Revision ID: 6a0b6d078ef0
Revises: 9096dd770bf8
Create Date: 2025-03-17 02:19:11.984354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0b6d078ef0'
down_revision: Union[str, None] = '9096dd770bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase', sa.Column('input_file_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testcase', 'input_file_content')
    # ### end Alembic commands ###
