"""return to origin3

Revision ID: 6c19e8cf7e4d
Revises: c1a5e15b21e0
Create Date: 2025-02-21 12:51:58.896479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c19e8cf7e4d'
down_revision: Union[str, None] = 'c1a5e15b21e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase', sa.Column('testcase_id', sa.String(), nullable=False))
    op.add_column('testcase', sa.Column('testcase_number', sa.Integer(), nullable=False))
    op.drop_index('ix_testcase_test_case_id', table_name='testcase')
    op.drop_constraint('result_test_case_id_fkey', 'result', type_='foreignkey')
    op.drop_constraint('input_file_content_test_case_id_fkey', 'input_file_content', type_='foreignkey')
    op.drop_column('testcase', 'test_case_id')
    op.create_primary_key(None, 'testcase', ['testcase_id'])
    op.create_index(op.f('ix_testcase_problem_id'), 'testcase', ['problem_id'], unique=False)
    op.drop_index('ix_testcase_with_path_testcase_with_path_id', table_name='testcase_with_path')
    op.create_index(op.f('ix_testcase_with_path_problem_id'), 'testcase_with_path', ['problem_id'], unique=False)
    op.alter_column('testcase_with_path', 'testcase_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('testcase_with_path', 'testcase_with_path_id')
    op.create_primary_key(None, 'testcase_with_path', ['testcase_id'])
    op.create_foreign_key(None, 'testcase', 'testcase_with_path', ['testcase_id'], ['testcase_id'])
    op.add_column('testcase_with_path', sa.Column('testcase_number', sa.Integer(), nullable=False))

    op.add_column('input_file_content', sa.Column('testcase_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'input_file_content', 'testcase', ['testcase_id'], ['testcase_id'])
    op.drop_column('input_file_content', 'test_case_id')
    op.add_column('result', sa.Column('testcase_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'result', 'testcase', ['testcase_id'], ['testcase_id'])
    op.drop_column('result', 'test_case_id')
    op.drop_index('ix_submission_submission_id', table_name='submission')
    op.create_index(op.f('ix_submission_user_name'), 'submission', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase_with_path', sa.Column('testcase_with_path_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_testcase_with_path_problem_id'), table_name='testcase_with_path')
    op.create_index('ix_testcase_with_path_testcase_with_path_id', 'testcase_with_path', ['testcase_with_path_id'], unique=False)
    op.alter_column('testcase_with_path', 'testcase_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('testcase_with_path', 'testcase_number')
    op.add_column('testcase', sa.Column('test_case_id', sa.INTEGER(), server_default=sa.text("nextval('testcase_test_case_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'testcase', type_='foreignkey')
    op.drop_index(op.f('ix_testcase_problem_id'), table_name='testcase')
    op.create_index('ix_testcase_test_case_id', 'testcase', ['test_case_id'], unique=False)
    op.drop_column('testcase', 'testcase_number')
    op.drop_column('testcase', 'testcase_id')
    op.drop_index(op.f('ix_submission_user_name'), table_name='submission')
    op.create_index('ix_submission_submission_id', 'submission', ['submission_id'], unique=False)
    op.add_column('result', sa.Column('test_case_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.create_foreign_key('result_test_case_id_fkey', 'result', 'testcase', ['test_case_id'], ['test_case_id'])
    op.drop_column('result', 'testcase_id')
    op.add_column('input_file_content', sa.Column('test_case_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'input_file_content', type_='foreignkey')
    op.create_foreign_key('input_file_content_test_case_id_fkey', 'input_file_content', 'testcase', ['test_case_id'], ['test_case_id'])
    op.drop_column('input_file_content', 'testcase_id')
    # ### end Alembic commands ###
