"""make submission independent

Revision ID: 7fad88df47bd
Revises: e5281eab9569
Create Date: 2025-02-18 21:17:40.286110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fad88df47bd'
down_revision: Union[str, None] = 'e5281eab9569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('result_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_result_result_id'), 'result', ['result_id'], unique=False)
    op.create_foreign_key(None, 'result', 'testcase', ['test_case_id'], ['test_case_id'])
    op.drop_constraint('submission_user_name_fkey', 'submission', type_='foreignkey')
    op.drop_constraint('submission_problem_id_fkey', 'submission', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('submission_problem_id_fkey', 'submission', 'problems', ['problem_id'], ['problem_id'])
    op.create_foreign_key('submission_user_name_fkey', 'submission', 'users', ['user_name'], ['user_name'])
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_index(op.f('ix_result_result_id'), table_name='result')
    op.drop_column('result', 'result_id')
    # ### end Alembic commands ###
