"""initial migration

Revision ID: 9096dd770bf8
Revises: 
Create Date: 2025-03-14 18:53:32.666342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9096dd770bf8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('is_petit_coder', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=False),
    sa.Column('memory_limit', sa.Integer(), nullable=False),
    sa.Column('input_format', sa.Text(), nullable=True),
    sa.Column('output_format', sa.Text(), nullable=True),
    sa.Column('open_date', sa.String(), nullable=True),
    sa.Column('close_date', sa.String(), nullable=True),
    sa.Column('border_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('problem_id')
    )
    op.create_index(op.f('ix_problems_problem_id'), 'problems', ['problem_id'], unique=False)
    op.create_table('users',
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_fullname', sa.String(), nullable=False),
    sa.Column('user_grade', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_name')
    )
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    op.create_table('image_paths',
    sa.Column('image_path_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_fullname', sa.String(), nullable=False),
    sa.Column('user_grade', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_name'], ['users.user_name'], ),
    sa.PrimaryKeyConstraint('image_path_id')
    )
    op.create_table('submission',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('submitted_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('compile_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.problem_id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['users.user_name'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_submission_user_name'), 'submission', ['user_name'], unique=False)
    op.create_table('testcase_with_path',
    sa.Column('testcase_id', sa.String(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('testcase_number', sa.Integer(), nullable=False),
    sa.Column('args_file_path', sa.String(), nullable=False),
    sa.Column('stdin_file_path', sa.String(), nullable=False),
    sa.Column('input_file_path', sa.String(), nullable=False),
    sa.Column('output_file_name', sa.String(), nullable=False),
    sa.Column('answer_file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.problem_id'], ),
    sa.PrimaryKeyConstraint('testcase_id')
    )
    op.create_index(op.f('ix_testcase_with_path_problem_id'), 'testcase_with_path', ['problem_id'], unique=False)
    op.create_table('input_file_content',
    sa.Column('testcase_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['testcase_id'], ['testcase_with_path.testcase_id'], ),
    sa.PrimaryKeyConstraint('testcase_id')
    )
    op.create_table('submission_result',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('testcase_number', sa.Integer(), nullable=False),
    sa.Column('output_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.submission_id'], ),
    sa.PrimaryKeyConstraint('submission_id', 'testcase_number')
    )
    op.create_table('submission_with_problem_name',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('problem_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.problem_id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.submission_id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['users.user_name'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('submitted_file',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.submission_id'], ),
    sa.PrimaryKeyConstraint('submission_id', 'name')
    )
    op.create_table('testcase',
    sa.Column('testcase_id', sa.String(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('testcase_number', sa.Integer(), nullable=False),
    sa.Column('args_file_content', sa.Text(), nullable=False),
    sa.Column('stdin_file_content', sa.Text(), nullable=False),
    sa.Column('answer_file_content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.problem_id'], ),
    sa.ForeignKeyConstraint(['testcase_id'], ['testcase_with_path.testcase_id'], ),
    sa.PrimaryKeyConstraint('testcase_id')
    )
    op.create_index(op.f('ix_testcase_problem_id'), 'testcase', ['problem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testcase_problem_id'), table_name='testcase')
    op.drop_table('testcase')
    op.drop_table('submitted_file')
    op.drop_table('submission_with_problem_name')
    op.drop_table('submission_result')
    op.drop_table('input_file_content')
    op.drop_index(op.f('ix_testcase_with_path_problem_id'), table_name='testcase_with_path')
    op.drop_table('testcase_with_path')
    op.drop_index(op.f('ix_submission_user_name'), table_name='submission')
    op.drop_table('submission')
    op.drop_table('image_paths')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_problems_problem_id'), table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###
