"""fukugou primary key

Revision ID: 9877a9ee8efa
Revises: a41ff60a5156
Create Date: 2025-02-21 15:15:30.513134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9877a9ee8efa'
down_revision: Union[str, None] = 'a41ff60a5156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_file_content', sa.Column('problem_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_input_file_content_problem_id'), 'input_file_content', ['problem_id'], unique=False)
    op.create_foreign_key(None, 'input_file_content', 'problems', ['problem_id'], ['problem_id'])
    op.drop_column('submission_result', 'testcase_id')
    op.add_column('submission_result', sa.Column('testcase_id', sa.Integer(), nullable=False))
    op.drop_index('ix_submission_result_result_id', table_name='submission_result')
    op.drop_column('submission_result', 'result_id')
    op.drop_column('testcase', 'testcase_id')
    op.add_column('testcase', sa.Column('testcase_id', sa.Integer(), nullable=False))
    op.drop_column('testcase', 'testcase_number')
    op.create_primary_key(None, 'testcase', ['problem_id', 'testcase_id'])
    op.drop_constraint('input_file_content_testcase_id_fkey', 'input_file_content', type_='foreignkey')
    op.drop_column('testcase_with_path', 'testcase_id')
    op.add_column('testcase_with_path', sa.Column('testcase_id', sa.Integer(), nullable=False))
    op.create_primary_key(None, 'testcase_with_path', ['problem_id', 'testcase_id'])
    op.drop_column('testcase_with_path', 'testcase_number')
    op.create_primary_key(None, 'input_file_content', ['problem_id', 'testcase_id', 'file_name'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase_with_path', sa.Column('testcase_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('testcase_with_path', 'testcase_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('testcase', sa.Column('testcase_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('testcase', 'testcase_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('submission_result', sa.Column('result_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_submission_result_result_id', 'submission_result', ['result_id'], unique=False)
    op.alter_column('submission_result', 'testcase_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'input_file_content', type_='foreignkey')
    op.drop_index(op.f('ix_input_file_content_problem_id'), table_name='input_file_content')
    op.drop_column('input_file_content', 'problem_id')
    # ### end Alembic commands ###
