"""return 4

Revision ID: 9973ce4e1469
Revises: 9877a9ee8efa
Create Date: 2025-02-21 15:36:24.619134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9973ce4e1469'
down_revision: Union[str, None] = '9877a9ee8efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_input_file_content_problem_id', table_name='input_file_content')
    op.drop_constraint('input_file_content_problem_id_fkey', 'input_file_content', type_='foreignkey')
    op.add_column('testcase_with_path', sa.Column('testcase_number', sa.Integer(), nullable=False))
    op.drop_column('testcase_with_path', 'testcase_id')
    op.add_column('testcase_with_path', sa.Column('testcase_id', sa.String(), nullable=False))
    op.drop_column('input_file_content', 'problem_id')
    op.drop_column('submission_result', 'testcase_id')
    op.add_column('submission_result', sa.Column('testcase_id', sa.String(), nullable=False))
    op.create_primary_key(None, 'testcase_with_path', ['testcase_id'])
    op.create_foreign_key(None, 'submission_result', 'testcase_with_path', ['testcase_id'], ['testcase_id'])
    op.add_column('testcase', sa.Column('testcase_number', sa.Integer(), nullable=False))
    op.alter_column('testcase', 'testcase_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'testcase', 'testcase_with_path', ['testcase_id'], ['testcase_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testcase_with_path', 'testcase_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('testcase_with_path', 'testcase_number')
    op.drop_constraint(None, 'testcase', type_='foreignkey')
    op.alter_column('testcase', 'testcase_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('testcase', 'testcase_number')
    op.drop_constraint(None, 'submission_result', type_='foreignkey')
    op.alter_column('submission_result', 'testcase_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('input_file_content', sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'input_file_content', type_='foreignkey')
    op.create_foreign_key('input_file_content_problem_id_fkey', 'input_file_content', 'problems', ['problem_id'], ['problem_id'])
    op.create_index('ix_input_file_content_problem_id', 'input_file_content', ['problem_id'], unique=False)
    # ### end Alembic commands ###
