"""eeyann2

Revision ID: a41ff60a5156
Revises: b2857bcdecbf
Create Date: 2025-02-21 14:09:15.280554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41ff60a5156'
down_revision: Union[str, None] = 'b2857bcdecbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase', sa.Column('args_file_content', sa.Text(), nullable=False))
    op.drop_column('testcase', 'args_file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase', sa.Column('args_file_path', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('testcase', 'args_file_content')
    # ### end Alembic commands ###
