"""changed testcase_with_path.input_file_path_list to testcase_with_path.input_file_path

Revision ID: bc8481ab8be9
Revises: 01f672b68b36
Create Date: 2025-02-24 16:38:08.255520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8481ab8be9'
down_revision: Union[str, None] = '01f672b68b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase_with_path', sa.Column('input_file_path', sa.String(), nullable=False))
    op.drop_column('testcase_with_path', 'input_file_path_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase_with_path', sa.Column('input_file_path_list', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('testcase_with_path', 'input_file_path')
    # ### end Alembic commands ###
