"""modified testcase_with_path

Revision ID: c4bd6bd1ed0c
Revises: 7fad88df47bd
Create Date: 2025-02-20 18:32:45.126186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4bd6bd1ed0c'
down_revision: Union[str, None] = '7fad88df47bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase_with_path', sa.Column('testcase_with_path_id', sa.Integer(), nullable=False))
    op.add_column('testcase_with_path', sa.Column('testcase_id', sa.Integer(), nullable=False))
    op.drop_index('ix_testcase_with_path_test_case_id', table_name='testcase_with_path')
    op.create_index(op.f('ix_testcase_with_path_testcase_with_path_id'), 'testcase_with_path', ['testcase_with_path_id'], unique=False)
    op.drop_column('testcase_with_path', 'test_case_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase_with_path', sa.Column('test_case_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_testcase_with_path_testcase_with_path_id'), table_name='testcase_with_path')
    op.create_index('ix_testcase_with_path_test_case_id', 'testcase_with_path', ['test_case_id'], unique=False)
    op.drop_column('testcase_with_path', 'testcase_id')
    op.drop_column('testcase_with_path', 'testcase_with_path_id')
    # ### end Alembic commands ###
