"""all_entity

Revision ID: e5281eab9569
Revises: b12121aa8de1
Create Date: 2025-02-10 01:53:57.107338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5281eab9569'
down_revision: Union[str, None] = 'b12121aa8de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_with_testcase',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=False),
    sa.Column('memory_limit', sa.Integer(), nullable=False),
    sa.Column('input_format', sa.Text(), nullable=True),
    sa.Column('output_format', sa.Text(), nullable=True),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('border_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('problem_id')
    )
    op.create_index(op.f('ix_problem_with_testcase_problem_id'), 'problem_with_testcase', ['problem_id'], unique=False)
    op.create_table('problems',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('is_petit_coder', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=False),
    sa.Column('memory_limit', sa.Integer(), nullable=False),
    sa.Column('input_format', sa.Text(), nullable=True),
    sa.Column('output_format', sa.Text(), nullable=True),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('border_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('problem_id')
    )
    op.create_index(op.f('ix_problems_problem_id'), 'problems', ['problem_id'], unique=False)
    op.create_table('submission',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.problem_id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['users.user_name'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_submission_submission_id'), 'submission', ['submission_id'], unique=False)
    op.create_table('testcase',
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('args_file_content', sa.Text(), nullable=False),
    sa.Column('stdin_file_content', sa.Text(), nullable=False),
    sa.Column('answer_file_content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem_with_testcase.problem_id']),
    sa.PrimaryKeyConstraint('test_case_id')
    )
    op.create_index(op.f('ix_testcase_test_case_id'), 'testcase', ['test_case_id'], unique=False)
    op.create_table('testcase_with_path',
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('args_file_path', sa.String(), nullable=False),
    sa.Column('stdin_file_path', sa.String(), nullable=False),
    sa.Column('input_file_path_list', sa.String(), nullable=True),
    sa.Column('output_file_name', sa.String(), nullable=False),
    sa.Column('answer_file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.problem_id'], ),
    sa.PrimaryKeyConstraint('test_case_id')
    )
    op.create_index(op.f('ix_testcase_with_path_test_case_id'), 'testcase_with_path', ['test_case_id'], unique=False)
    op.create_table('input_file_content',
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['testcase.test_case_id'], ),
    sa.PrimaryKeyConstraint('test_case_id', 'file_name')
    )
    op.create_table('result',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.submission_id'], ),
    sa.PrimaryKeyConstraint('submission_id', 'test_case_id')
    )
    op.create_table('submission_with_problem_name',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('problem_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.problem_id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.submission_id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['users.user_name'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('submitted_file',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.submission_id'], ),
    sa.PrimaryKeyConstraint('submission_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submitted_file')
    op.drop_table('submission_with_problem_name')
    op.drop_table('result')
    op.drop_table('input_file_content')
    op.drop_index(op.f('ix_testcase_with_path_test_case_id'), table_name='testcase_with_path')
    op.drop_table('testcase_with_path')
    op.drop_index(op.f('ix_testcase_test_case_id'), table_name='testcase')
    op.drop_table('testcase')
    op.drop_index(op.f('ix_submission_submission_id'), table_name='submission')
    op.drop_table('submission')
    op.drop_index(op.f('ix_problems_problem_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_problem_with_testcase_problem_id'), table_name='problem_with_testcase')
    op.drop_table('problem_with_testcase')
    # ### end Alembic commands ###
